// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw2uDyR0wng6TzCh663u8Cfs5z8imr8bI',
    appId: '1:91950588356:web:7313595ff6aaab6f854491',
    messagingSenderId: '91950588356',
    projectId: 'chat-app-4fbd4',
    authDomain: 'chat-app-4fbd4.firebaseapp.com',
    storageBucket: 'chat-app-4fbd4.firebasestorage.app',
    measurementId: 'G-G27FJ4GPYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh-ABTY18kwiU5p-s-02wMgUuIq6E-6Ew',
    appId: '1:91950588356:android:d623a6130ac6cfd2854491',
    messagingSenderId: '91950588356',
    projectId: 'chat-app-4fbd4',
    storageBucket: 'chat-app-4fbd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtAOaOl27TgTGmiuDYSDTsKFbX6Tt2QGg',
    appId: '1:91950588356:ios:c473f897e4ba2f23854491',
    messagingSenderId: '91950588356',
    projectId: 'chat-app-4fbd4',
    storageBucket: 'chat-app-4fbd4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtAOaOl27TgTGmiuDYSDTsKFbX6Tt2QGg',
    appId: '1:91950588356:ios:c473f897e4ba2f23854491',
    messagingSenderId: '91950588356',
    projectId: 'chat-app-4fbd4',
    storageBucket: 'chat-app-4fbd4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw2uDyR0wng6TzCh663u8Cfs5z8imr8bI',
    appId: '1:91950588356:web:e40cebe2466c6c3d854491',
    messagingSenderId: '91950588356',
    projectId: 'chat-app-4fbd4',
    authDomain: 'chat-app-4fbd4.firebaseapp.com',
    storageBucket: 'chat-app-4fbd4.firebasestorage.app',
    measurementId: 'G-1KWD4BKR5E',
  );
}
